---
name: integration-api-build
run-name: Build and run test suites
on:
  push:
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: quay.io/bluebird/java-builder:ubuntu.0.1.5.jdk-17.b21
        steps:
          - uses: actions/checkout@v4
          - name: Add workspace to git safe.directory
            run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
          - name: Cleaning project for quick validation
            run: make libyear
          - name: Build Integration API
            run: make
          - name: Run integration and unit test suite
            run: make tests
          - name: Collect test results
            run: make collect-testresults
          - name: Publish Unit Test Report
            if: always()
            uses: scacap/action-surefire-report@v1
            with:
              check_name: Test Report
          - name: Persist build artifacts
            uses: actions/upload-artifact@v4
            with:
              name: build-artifacts
              path: target/artifacts